### ISSUE TITLE
Limitation of integrating a new environment in persona (Production - Staging)

### ISSUE THREAD

**Issue by HarithaMadhushanka** [jorgefspereira/persona_flutter#34]
We got a new environment from persona called **'Production - Staging'**. But in the Persona Flutter SDK the only available enums of **InquiryEnvironment** are **sandbox** and **production**.

How do we send the **Production - Staging** using the persona flutter SDK?

<img width="569" alt="Screenshot 2023-11-20 at 12 13 55 PM" src="https://github.com/jorgefspereira/persona_flutter/assets/24701389/e424f981-6f78-4117-ba63-d775230eda9c">

<img width="920" alt="Screenshot 2023-11-20 at 11 56 42 AM" src="https://github.com/jorgefspereira/persona_flutter/assets/24701389/d41b9869-5df5-4f34-8bf8-3fcd7712cae8">

![284127358-cabbaa9d-2af1-4d39-b18a-35bf82e9ac0e](https://github.com/jorgefspereira/persona_flutter/assets/24701389/8120d1cc-445c-4490-a356-507e17f50a62)

**Comment by jorgefspereira** [comment]
Hi @HarithaMadhushanka 

You probably should contact the persona support for this case, since their native sdk the only allowed environment values are staging and production.

![Screenshot 2023-11-22 at 14 33 56](https://github.com/jorgefspereira/persona_flutter/assets/11697952/226b0077-cbff-41b1-93cc-31e7cb1a9c93)

Fell free to pull request the solution for your problem or ping me if you need any changes to the plugin.

**Comment by ChanakaWeerasinghe** [comment]
Hi @jorgefspereira 

We have gone through the persona documentation. In their documentation, there is a place to add the environmentId. However, we are currently struggling with how to pass the environmentId. Could you please help us? about this concern

<img width="861" alt="Screenshot 2023-11-29 at 11 42 27 AM" src="https://github.com/jorgefspereira/persona_flutter/assets/20734864/88e46f22-fac6-4585-b55e-c67dc4483868">
